apiVersion: v1
kind: Service
metadata:
  name: product-page
  labels:
    app: product-page
spec:
  type: NodePort
  ports:
  - name: '3000'
    port: 3000
    targetPort: 3000
  selector:
    app: product-page